### ISSUE TITLE
极简示例中权重策略的分配测试问题

### ISSUE THREAD

**Issue by caicaisir** [Nepxion/DiscoveryGray#1]
极简示例中权重策略的分配测试无论是网关的还是全链路的，都没有成功，一直都在轮询。使用的版本后是5.1.2的，是我测试方法不对还是该版本没这个功能呢？

**Comment by HaojunRen** [comment]
极简示例只针对5.2.0，但目前还是SNAPSHOT版，请引入Discovery源码，下周将发布5.2.0正式版
