### ISSUE TITLE
zuul 使用线程池隔离时，RequestContext 上下文会丢失

### ISSUE THREAD

**Issue by jackorjack** [Nepxion/DiscoveryGray#2]
![~30L0X159CHF@5P3~ KALON](https://user-images.githubusercontent.com/29791881/60571611-8dc2da00-9da6-11e9-875a-488be31534aa.png)

在获取com.nepxion.discovery.plugin.strategy.zuul.context.ZuulStrategyContextHolder#getZuulRequestHeaders 中RequestContext 中 getZuulRequestHeaders 头的信息时，获取不到值，debug会发现，filter中 RequestContext  对象 和这里获取的 RequestContext  地址已经不是同一个地址，导致获取不到head中的版本信息，不能按规则去路由

**Comment by jackorjack** [comment]
这个有依赖，spring.application.strategy. hystrix.threadlocal.supported=true也配置了

**Comment by HaojunRen** [comment]
n-d-version从界面传入了么？

**Comment by jackorjack** [comment]
没有，只是实现了ZuulStrategyRouteFilter 重写了getRouteVersion 方法

**Comment by HaojunRen** [comment]
微信 1394997
